### ISSUE TITLE
Alarm Card fails to render

### ISSUE THREAD

**Issue by konradwalsh** [neilimixamo/Home-Assistant-Quick-Look-Mobile#1]
![image](https://github.com/neilimixamo/Home-Assistant-Quick-Look-Mobile/assets/7996482/b715a5cd-e750-46f5-851d-f8394de35f54)

I am getting this error.

This is the code I added my alarm panel to
````
  - type: custom:button-card # FOOTER TITLE
    view_layout:
      grid-area: footer_title
    template: title_sticky
    variables:
      title: 'Alarm' #can be changed
  - type: custom:button-card # FOOTER
    view_layout:
      grid-area: footer
    template: alarm
    variables:
      entity: alarm_control_panel.visonic_alarm
  - type: custom:button-card # MENU
    view_layout:
      grid-area: menu
    template: menu
````

I triple checked the spelling for the alarm entity
