### ISSUE TITLE
Enlarge scrollable area

### ISSUE THREAD

**Issue by hAMMERlized** [neilimixamo/Home-Assistant-Quick-Look-Mobile#11]
Hey @neilimixamo mate,

sorry for spamming you so hard lately but I can't find the code I have to edit / delete to make the thing work like I would like to.

As I am not using scenes manually and I don't need the toolbar at the bottom I would like to enlarge the scrollable area at the "Home" section, or maybe even at some other sections too, not sure. Maybe I am going to use it in a other kind of way. Okay anyway...

How do I delete the footer area / enlarge the scrollable area as there would be more space for some entities displaying without scrolling.

Thanks... again 😄

![image](https://github.com/neilimixamo/Home-Assistant-Quick-Look-Mobile/assets/95163968/d84ea80a-0ebc-4290-bfa6-57deb7f9d2be)

**Comment by neilimixamo** [comment]
Vertical spacing in sections is defined at the beginning of each view like this :

![image](https://github.com/neilimixamo/Home-Assistant-Quick-Look-Mobile/assets/43101688/80ff4f42-e141-4b7c-9a36-f2cf62cb4648)

To include the footer section within the main section, you need to modify the layout in this way : 

```yaml
layout:
  margin: -0.5vh 1vh 0vh
  grid-template-columns: auto
  grid-template-rows: 19.5vh 5.5vh 4.6vh 61.4vh 9vh
  grid-template-areas: |
    "header"
    "subheader"
    "main_title"
    "main"
    "menu"
```

The main section also has an additional particularity: you need to specify its new height (61.4vh) lower down in the configuration : 

```yaml
  - type: custom:layout-card # MAIN
    view_layout:
      grid-area: main
    layout_type: custom:vertical-layout
    layout:
      height: 61.4vh
      margin: 0vh 0vh 0vh
      padding: 0vh 0.4vh
```

I can see in your screenshot that you left empty vertical space between multiple cards, and I assume you would like to display a title there. This can be easily achieved by adding a "title_scrollable" template card at the desired location within the MAIN section:

```yaml Add
  - type: custom:layout-card # MAIN
    view_layout:
      grid-area: main
    layout_type: custom:vertical-layout
    layout:
      height: 61.4vh
      margin: 0vh 0vh 0vh
      padding: 0vh 0.4vh
    cards:
      - type: grid
        columns: 2
        square: false
        cards:
          - type: custom:button-card # ENTITY 01
            template: 
            variables:
              entity: 
              name: 
              label: 
          - type: custom:button-card # ENTITY 02
            template:
            variables:
              entity:
              name: 
              label:
      - type: custom:button-card # TITLE
        template: title_scrollable
        variables:
          title: 
      - type: grid
        columns: 2
        square: false
        cards:
          - type: custom:button-card # ENTITY 03
            template: device
            variables:
              entity:
              name: 
              label:
          - type: custom:button-card # ENTITY 04
            template: device
            variables:
              entity:
              name: 
              label:

```

Your main cards appear with a shorter height compared to mine. As I'm still curious about the default view that each user may have, could you please confirm if you intentionally reduced their size for practicality?

**Comment by hAMMERlized** [comment]
Thanks once again for your help. Scrollbar works now like a charm. As you've mentioned right I wanted to use some titles between the entities and wit your code it works as expected. I was still doing some trial and error but couldn't achieve to get it at the right place.

Button Card is still new to me and I am trying to dive deeper and deeper into it :)

> Your main cards appear with a shorter height compared to mine. As I'm still curious about the default view that each user may have, could you please confirm if you intentionally reduced their size for practicality?

No worrys, your code is all right. I just tweaked the cards and layout a bit to get a view that I like. Personally I like it clean (like your dashboard already is) and more or less compact with displaying "important" infos at the main page without the need of diving deeper as needed into the dashboards subviews. But that's just my personal expectation.

I have just one problem. As the first title in the main part is "static" it is not hiding while scrolling through the entities.

Tried to put the title code snippet to the right place but so far I couldn't handle it. Hope you know what I mean.


Best Regards,
Sebastian

**Comment by neilimixamo** [comment]
Ok, I see, to replace the first sticky title by a scrollable one, you will need to modify the layout again by incorporating the space reserved for the "main_title" within the "main" section. Additionally, add "Anwesenheit" title as the first item within the "main" section, like this : 

```
layout:
  margin: -0.5vh 1vh 0vh
  grid-template-columns: auto
  grid-template-rows: 19.5vh 5.5vh 66vh 9vh
  grid-template-areas: |
    "header"
    "subheader"
    "main"
    "menu"
```
Then : 

```yaml
  - type: custom:layout-card # MAIN
    view_layout:
      grid-area: main
    layout_type: custom:vertical-layout
    layout:
      height: 66vh #################### IMPORTANT
      margin: 0vh 0vh 0vh
      padding: 0vh 0.4vh
    cards:
      - type: custom:button-card # TITLE 01
        template: title_scrollable
        variables:
          title: Anwesenheit
      - type: grid
        columns: 2
        square: false
        cards:
          - type: custom:button-card # ENTITY 01
            template: 
            variables:
              entity:
              name: 
          - type: custom:button-card # ENTITY 02
            template:
            variables:
              entity:
              name:
      - type: custom:button-card # TITLE 02
        template: title_scrollable
        variables:
          title: Klima
      - type: grid
        columns: 2
        square: false
        cards:
          - type: custom:button-card # ENTITY 03
            template: 
            variables:
              entity:
              name: 
          - type: custom:button-card # ENTITY 04
            template:
            variables:
              entity:
              name:
```

This will become the default view in the 2.0.0 update as I believe it will be more practical.

**Comment by hAMMERlized** [comment]
Sorry to repost this closed issue but I have another little problem. I am now at the `light_bulbs_room1.yaml`.

I can't get the title and the chevron at the same row. Is there a new code snippet needed or just a matter on where to put the code?  Thanks.

![image](https://github.com/neilimixamo/Home-Assistant-Quick-Look-Mobile/assets/95163968/198eac5c-3d07-413a-91e1-0b41f0f26043)

**Comment by neilimixamo** [comment]
if Wohnzimmer icorresponds to the subheader area, add the chevron code after (native) line 34 and replace `grid-area: main_title`  with `grid-area: subheader` and `bottom: 0.3vh` with `top: 1vh` like this : 

```yaml
  - type: custom:button-card # CHEVRON-LEFT
    view_layout:
      grid-area: subheader
    icon: mdi:chevron-left
    color: var(--chevron-color)
    size: 65%
    styles:
      card:
        - background: transparent
        - box-shadow: none
        - border-radius: 50%
        - height: 4.6vh
        - width: 4.6vh
        - left: 82vw
        - top: 1vh
    tap_action:
      action: navigate
      navigation_path: 'light_bulbs'
```

**Comment by hAMMERlized** [comment]
I am using `subheader` neither. I only use `header`, `meain` and `menu`. That's my code inside the yaml file so far:

`title: lights_bulbs_room1 #change "room1" by your room name
path: light_bulbs_room1 #change "room1" by tour room name
icon: mdi:lightbulb
theme: Quick Look Mobile
background: "white"
type: custom:grid-layout
layout:
  margin: -0.5vh 1vh 0vh
  grid-template-columns: auto
  grid-template-rows: 19.5vh 71.5vh 9vh
  grid-template-areas: |
    "header"
    "main"
    "menu"
cards:
  - type: custom:button-card # HEADER
    view_layout:
      grid-area: header
    template: header
    variables:
      view: light


  - type: custom:layout-card
    view_layout:
      grid-area: main
    layout_type: custom:vertical-layout
    layout:
      height: 71.5vh
      margin: 0vh 0vh 0vh
      padding: 0vh 0.4vh
    cards:


      - type: custom:button-card # CHEVRON-LEFT
        view_layout:
          grid-area: main
        icon: mdi:chevron-left
        color: darkgrey
        size: 65%
        styles:
          card:
            - background: transparent
            - box-shadow: none
            - border-radius: 50%
            - height: 4.6vh
            - width: 4.6vh
            - left: 82vw
            - bottom: 0.3vh
        tap_action:
          action: navigate
          navigation_path: "light_bulbs"
      - type: grid
        columns: 2
        square: false
        cards:


          - type: custom:button-card # ENTITY 01
            template: light
            variables:
              entity: light.wohnzimmer_hugo_links #requires light.entity
              name: Hugo links #optional
              label_on: #optional
              label_off: #optional
          - type: custom:button-card # ENTITY 02
            template: light
            variables:
              entity: light.wohnzimmer_hugo_rechts
              name: Hugo rechts
              label_on: true
              label_off:
          - type: custom:button-card # ENTITY 03
            template: light
            variables:
              entity: light.wohnzimmer_sofa
              name: Sofa
              label_on:
              label_off: true`

Sorry for being such an idiot :D

**Comment by neilimixamo** [comment]
Great, I can see that you have a good understanding of the layout concept. 

It's true that whitout subheader or main_title sections, the placement of the chevron in the main section will appear as a separate card positioned below the title. (By the way, I assume that you still want to include a title before placing the cards, as shown in your screenshot)

The workaround for this issue would be adding `- position: absolute` to the chevron code in order to achieve the desired layout : 

```yaml
title: lights_bulbs_room1 #change "room1" by your room name
path: light_bulbs_room1 #change "room1" by tour room name
icon: mdi:lightbulb
theme: Quick Look Mobile
background: "white"
type: custom:grid-layout
layout:
  margin: -0.5vh 1vh 0vh
  grid-template-columns: auto
  grid-template-rows: 19.5vh 71.5vh 9vh
  grid-template-areas: |
    "header"
    "main"
    "menu"      
cards:
  - type: custom:button-card # HEADER
    view_layout:
      grid-area: header
    template: header
    variables:
      view: light 
  - type: custom:layout-card # MAIN
    view_layout:
      grid-area: main
    layout_type: custom:vertical-layout
    layout:
      height: 71.5vh
      margin: 0vh 0vh 0vh
      padding: 0vh 0.4vh
    cards:
      - type: custom:button-card # TITLE
        template: title_scrollable
        variables:
          title: Wohnzimmer #can be changed
      - type: custom:button-card # CHEVRON-LEFT
        icon: mdi:chevron-left
        color: var(--chevron-color)
        size: 65%
        styles:
          card:
            - background: transparent
            - box-shadow: none
            - border-radius: 50%
            - height: 4.6vh
            - width: 4.6vh
            - left: 82vw
            - bottom: 0.3vh
            - position: absolute
        tap_action:
          action: navigate
          navigation_path: 'light_bulbs'
      - type: grid
        columns: 2
        square: false
        cards:
          - type: custom:button-card # ENTITY 01
            template: light
            variables:
              entity:  light.wohnzimmer_hugo_links #requires light.entity
              name: Hugo links #optional
          - type: custom:button-card # ENTITY 02
            template: light
            variables:
              entity: light.wohnzimmer_hugo_rechts
              name:
          - type: custom:button-card # ENTITY 03
            template: light
            variables:
              entity: light.wohnzimmer_sofa
              name: Sofa
```

Hope it will do the trick.

PS : you can add code like this

![image](https://github.com/neilimixamo/Home-Assistant-Quick-Look-Mobile/assets/43101688/9a8dab15-3f8f-48ef-b153-34412bc0dc3a)
