### ISSUE TITLE
Header have no count and color when device is active

### ISSUE THREAD

**Issue by kesm** [neilimixamo/Home-Assistant-Quick-Look-Mobile#15]
Hello, 

I guess I did the configuration wrong but I can't see what is missing. 
One of my light is configured this way: 

```
cards:
          - type: custom:button-card # ENTITY 01
            template: light #or 'light_expandable'
            variables:
              entity: light.entree #required light.entity_id
              name: Entrée #optional
              expand_to: #required path if light_expandable template is used
```
              
and homeassistant/custom_templates/quick_look_mobile_macros (v2.0.0).jinja   is configured this way

```
# LIGHTBULBS :
{% set light_entity_ids = [
  'light.entree',
] %}  
```   

I tried to restart homeassistant and reload custom theme but it doesn't seem to work
              
![image](https://github.com/neilimixamo/Home-Assistant-Quick-Look-Mobile/assets/6907912/d7918031-db56-4c08-86bf-d51903254791)

Any idea of what is going on?
