### ISSUE TITLE
Script after tap in persons view

### ISSUE THREAD

**Issue by Michelone86** [neilimixamo/Home-Assistant-Quick-Look-Mobile#28]
Hello @neilimixamo, I would like to run a script for each person present in the PERSONS card, when I press the arrow.

It's possible? Thank you 🙏
![Screenshot_20240508_130433](https://github.com/neilimixamo/Home-Assistant-Quick-Look-Mobile/assets/97887508/b9f94cd3-9089-4ff5-8d82-1cb15dd54732)

**Comment by neilimixamo** [comment]
Hi @Michelone86, the 'Routines' section at the bottom of each view is designed for easy triggering of 5 scripts, automations, and/or scenes and can be customized with icon, name and colors : 

```yaml
- type: custom:button-card # FOOTER
  view_layout:
    grid-area: footer
  template: routines_footer
  variables:
    routine1_entity: script.your_entity_id
    routine1_name: 
    routine1_background_color: 
    routine1_icon_color: 
    routine2_entity: automation.your_entity_id
    routine2_name: 
    routine2_background_color: 
    routine2_icon_color: 
    routine3_entity: scene.your_entity_id
    routine3_name:  
    routine3_background_color: 
    routine3_icon_color: 
    routine4_entity: 
    routine4_name: 
    routine4_background_color: 
    routine4_icon_color: 
    routine5_entity: 
    routine5_name: 
    routine5_background_color: 
    routine5_icon_color: 
```

However, if you specifically want to trigger a script by pressing the arrow integrated in the 'person' card, you can add the following code to it : 


```yaml
- type: custom:button-card # PERSON 01
  template: person_expandable #or "person"
  variables:
    entity: person.your_entity_id
    name: #optional
    label: #optional
    battery: #optional battery sensor to display as a badge when <60%
  custom_fields:
    chevron: 
      card:
        tap_action:
          action: call-service
          service: script.turn_on
          service_data:
            entity_id: script.your_entity_id
```

I hope this meets your expectations :)
