### ISSUE TITLE
Rapid Toggle Switch 

### ISSUE THREAD

**Issue by Michelone86** [neilimixamo/Home-Assistant-Quick-Look-Mobile#30]
Hello @neilimixamo, it would be interesting to insert a section with some Toggle switches for quickly activating some entities, which do not necessarily have to be lights, doors, routines, scripts, etc..

For example, in my home automation I created the guest mode. I activate this mode with a button when my parents from the south of Italy come to visit me at home (at Christmas 😊). Guest mode is a boolean switch that, when turned on, deactivates all the automations that usually activate when my wife and I are away from home.

Or a simple button restarts the modem (button entity of the Fritzbox).

In these two cases the keys would remain colored as long as the activations are in operation.

What do you think about it?  Thanks 😉

**Comment by neilimixamo** [comment]
Hi @Michelone86 , I think the current `device` template should be able to handle these two scenarios : 

1/ Regarding the 'input_boolean' entity, it should be recognized without any issues and will display a blue color when active and no color when inactive. 

```yaml
- type: custom:button-card # ENTITY 01
  template: device
  variables:
    entity: input_boolean.guest_mode
    name: 
    label_on: 'Active'
    label_off: 'Inactive'
```

2/ If I understand correctly, you want to be able to restart your modem by activating its 'button.modem_restart' entity and display the card in blue until it is fully rebooted. 

Managing the 'button' entity is not as straightforward since it doesn't have a binary on-off state. It also doesn't seem that the button waits for a complete reboot of the device before it can be clicked again, which would make managing the color of the card difficult as well. However, I believe there is a simple way to achieve what you're looking for, still via the 'device' template.

Instead of refering your 'button.modem_restart' as entity, you should refer the binary_sensor that looks for the connectivity of your modem. Perhaps your device already has a 'binary_sensor.modem_state'. If not, you can simply create this binary_sensor through the [Ping](https://www.home-assistant.io/integrations/ping/) integration by specifying the IP address of your modem.

At that point, the card will display a blue color when your modem is 'on' and a gray color when it's 'off'. 

Finally, adding the following code will easily allow you to activate its 'button' entity with a simple click on its icon

```yaml
- type: custom:button-card # ENTITY 02
  template: device
  variables:
    entity: binary_sensor.modem_state
    name: 
    label_on: 'Active'
    label_off: 'Inactive'
    icon_tap_action:
      action: call-service
      service: button.press
      service_data:
        entity_id: button.modem_restart
```

Try this out and let me know what you think. We can then fine-tune additional settings according to your preferences
