### ISSUE TITLE
Replacing Upper Right Assist Card

### ISSUE THREAD

**Issue by Michelone86** [neilimixamo/Home-Assistant-Quick-Look-Mobile#32]
Hi @neilimixamo, I want to replace the assistant function. I managed to change the icon and start a script, working on the header file in the template section. 
However, I would like a number taken from a specific numerical entity to appear at the top right of the mail icon.

How can I do? Thank you!

![Screenshot_20240520_181601_edit_663790113968761](https://github.com/neilimixamo/Home-Assistant-Quick-Look-Mobile/assets/97887508/3287e5fb-ab2d-49c8-8a87-cc31ce9b11ba)
![Screenshot_20240520_181707_edit_663831612987495](https://github.com/neilimixamo/Home-Assistant-Quick-Look-Mobile/assets/97887508/2e8dc899-f10a-4c45-b698-edb3682a7516)

**Comment by neilimixamo** [comment]
Yep, adding a mail counter is a nice idea, here is how to do it :

<details>
<summary>New header code </summary>

```yaml
right_menu:
  card:
    type: custom:button-card
    icon: mdi:mail
    size: 80%
    styles:
      card:
        - overflow: visible
        - height: 4.2vh
        - width: 4.2vh
        - box-shadow: none
        - border-radius: 50%
        - background-color: transparent
        - cursor: none
        - --mdc-ripple-press-opacity: 0
    custom_fields:
      badge:
        card:
          type: custom:button-card
          entity: counter.contatore_posta
          show_icon: false
          show_label: true
          show_name: false
          show_state: true
          styles:
            state:
              - font-size: 12px
              - font-weight: 500
              - color: var(--text)
              - display: flex
              - justify-content: center
              - align-items: center
            card:
              - height: 2.5vh
              - width: 2.5vh
              - border-radius: 50%
              - border: solid
              - border-width: 1px
              - position: absolute
              - top: -4.5vh
              - right: -1.0vw
              - background: 'var(--badge-background)'
              - border-color: 'var(--badge-border-color)'
              - box-shadow: 'none'
              - cursor: none
              - --mdc-ripple-press-opacity: 0
              - display: |
                  [[[ 
                    if (states['counter.contatore_posta'].state == 0) {
                      return 'none';
                    } else {
                      return 'flex';
                    }
                  ]]]
          tap_action: 
            action: none #disables unwanted tap_action on the badge
    tap_action:
      action: toggle
      entity: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

</details>

Just add your script entity at last line 👍
