### ISSUE TITLE
QLM on the Tablet

### ISSUE THREAD

**Issue by Michelone86** [neilimixamo/Home-Assistant-Quick-Look-Mobile#34]
Hi @neilimixamo, I would like to try adapting your Dashboard to use it on my tablet too. 
Which files should I duplicate and edit, without losing the current view I have on smartphones? I don't want to duplicate all the files because then I would have to edit the files twice every time I make some changes... Thank you 😉

**Comment by neilimixamo** [comment]
Hi @Michelone86 

This is nice, creating a tablet version is also on my to-do list, but I haven't had the opportunity to start on it yet. 

If you want to beta-test a tablet view while maintaining your current mobile dashboard, follow these steps:

1. Duplicate the `/dashboards/quick_look_mobile` folder and rename it to `/dashboards/quick_look_tablet`.

2. Add the following code to the `/dashboards/dashboards.yaml` file:

```yaml
quick-look-mobile-dashboard:
  mode: yaml
  title: Quick Look Mobile
  icon: mdi:cellphone
  show_in_sidebar: true
  filename: dashboards/quick_look_mobile/qlm.yaml

quick-look-tablet-dashboard:
  mode: yaml
  title: Quick Look Tablet
  icon: mdi:tablet
  show_in_sidebar: true
  filename: dashboards/quick_look_tablet/qlm.yaml

```

Keep in mind that any changes to the cards won't be synchronized between the mobile and tablet views.
