### ISSUE TITLE
Optional Humidity on climate cards

### ISSUE THREAD

**Issue by RealityTest** [neilimixamo/Home-Assistant-Quick-Look-Mobile#36]
I'm using temperature and humidity sensors that display the temperature for my climate control cards and it would be useful if the cards could also display humidity as an optional value right below or next to the temperature. Is there anything like this planned or would it be possible to add?

**Comment by neilimixamo** [comment]
![image](https://github.com/user-attachments/assets/7f6f07af-e0ab-4386-8b12-df8d269726a6)

Adding the following line of code as the climate label should do the trick : just replace `climate.lounge` (1) with your entity and, if necessary, `current_temperature` (2) and `current_humidity` (3) attributes to return the values you wish to display.

```yaml
- type: custom:button-card 
  template: climate
  variables:
    entity: climate.lounge
    name: Salon
    battery: 
    label: "[[[return states['climate.lounge'].attributes.current_temperature.toFixed(1) + ' °C' + ' - ' + states['climate.lounge'].attributes.current_humidity.toFixed(0) + '%' ]]]"
```


![image](https://github.com/user-attachments/assets/b9e74273-34f7-44e2-8e5f-a8ed02741f24)
