### ISSUE TITLE
Ideas: Button Dimension + 3 Columns

### ISSUE THREAD

**Issue by Marcoletto** [neilimixamo/Home-Assistant-Quick-Look-Mobile#40]
First of all I would like to congratulate with you for a great job and thank you for your time, also.

Is it possible to change the dimension (height) of the buttons and put them in 3 columns?

![ideas](https://github.com/user-attachments/assets/4c071096-bc62-4a89-b217-15153165896f)

**Comment by neilimixamo** [comment]
Hi @Marcoletto, thanks for the congrats !

I suggest you to change the values I'll indicate as follows:

```yaml
value: 7.0vh #10.8vh <------------------ indicates you should replace 10.8vh with 7.0vh`
```

First, you’ll need to update the number of columns to 3 for each view contained in `/dashboards/quick_look_mobile/views"

```yaml
      - type: grid
        columns: 3  #2 <------------------
        square: false
        cards: 
```

Next, you’ll need to adjust the dimensions of the card model in both `/dashboards/quick_look_mobile/templates/basic_card` + `basic_card_expandable.yaml`

```yaml
basic_card:
  variables:
    entity:
    name:
  show_icon: false
  show_name: false
  triggers_update: all
  styles:
    card:
      - height: 7.0vh #10.8 <------------------
      - padding: 0px
      - border-radius:  14px #27px <------------------
      - cursor: none
      - --mdc-ripple-press-opacity: 0
      - box-shadow: none
    grid:
      - grid-template-columns: 46% 54%
      - grid-template-rows: 1fr
      - grid-template-areas: '"icon name"'
      - align-items: center
      - justify-items: center
  custom_fields:
    slider_visible: 
      card: 
        type: custom:my-slider-v2
        styles:
          card:
            - display: none
    icon:
      card:
        type: custom:button-card # ICON
        entity: '[[[ return variables.entity ]]]'
        show_name: false
        size: 50%
        styles:
          card:
            - height: 4vh #6vh <------------------
            - width: 4vh #6vh <------------------
            - border-radius: 50%
            - box-shadow: none
            - cursor: none 
            - --mdc-ripple-press-opacity: 0 
        tap_action: |
            [[[ 
              if (variables.icon_tap_action) {
                return variables.icon_tap_action;
              } else {
                return { action: 'toggle' };
              }
            ]]]
        double_tap_action: |
          [[[
            if (variables.icon_double_tap_action) {
              return variables.icon_double_tap_action;
            } else {
              return { action: 'none' };
            }
          ]]]
        hold_action: |
          [[[
            if (variables.icon_hold_action) {
              return variables.icon_hold_action;
            } else {
              return { action: 'none' };
            }
          ]]]
    name:
      card:
        type: custom:button-card # NAME & LABEL
        entity: '[[[ return variables.entity ]]]'
        name: |
          [[[
            if (variables.name) {
              return variables.name;
            } else if (variables.entity) {
                return states[variables.entity].attributes.friendly_name;
            } else {
                return 'Name';
            }
          ]]]
        show_icon: false
        show_label: true
        styles:
          card:
            - height: 7vh #10.8vh <------------------
            - width: 29.2vw
            - background-color: transparent
            - border-radius: 0%
            - box-shadow: none
            - cursor: none 
            - --mdc-ripple-press-opacity: 0 
          name: 
            - font-size: 11px #14px <------------------
            - font-weight: 500
            - justify-self: start
            - padding-left: 0vw
          label: 
            - font-size: 10px #12px <------------------
            - font-weight: 400
            - justify-self: start
            - padding-left: 0vw
            - padding-top: 0.5vh
        tap_action: |
            [[[
              if (variables.name_tap_action) {
                return variables.name_tap_action;
              } else {
                return { action: 'more-info' };
              }
            ]]]
        double_tap_action: |
          [[[
            if (variables.name_double_tap_action) {
              return variables.name_double_tap_action;
            } else {
              return { action: 'none' };
            }
          ]]]
        hold_action: |
          [[[
            if (variables.name_hold_action) {
              return variables.name_hold_action;
            } else {
              return { action: 'none' };
            }
          ]]]
```

Of course, feel free to tweak these new values to better match the design you’re aiming for. Don’t hesitate to let me know if you encounter any issues after implementing these changes.
