### ISSUE TITLE
add cover_expandable like light_expandable

### ISSUE THREAD

**Issue by kesm** [neilimixamo/Home-Assistant-Quick-Look-Mobile#9]
Hello, 

light_expandable is a great system to have multiple bulbs in one cell, it could be great to have the same behavior for covers: in my case I have two covers in my living room and I would like to be able to manage them by group or individually

**Comment by neilimixamo** [comment]
HI @kesm, 

Here it is : add the new [cover_expandable (v1.0).yaml](https://github.com/neilimixamo/Home-Assistant-Quick-Look-Mobile/blob/main/dashboards/quick_look_mobile/templates/cards/cover_expandable%20(v1.0).yaml) to your `templates` folder then add this new view [4.5_light_covers_room1.yaml](https://github.com/neilimixamo/Home-Assistant-Quick-Look-Mobile/blob/main/dashboards/quick_look_mobile/views/4.5_light_covers_room1.yaml) to your `views` folder

This will make this possible : 

```yaml
          - type: custom:button-card # ENTITY 01
            template: cover
            variables:
              entity:
              name:
          - type: custom:button-card # ENTITY 02 (EXPANDABLE)
            template: cover_expandable
            variables:
              entity:
              name:
              expandable_towards: light_covers_room1
```

I hope this meets your expectations.
